"""add_recipe_image_url

Revision ID: 305e0c3cd62a
Revises: 23965e07596e
Create Date: 2026-07-09 22:50:44.321007
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "305e0c3cd62a"
down_revision: str | None = "23965e07596e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_organizations_slug"), table_name="organizations")
    op.create_index(
        op.f("ix_organizations_slug"), "organizations", ["slug"], unique=True
    )
    op.add_column(
        "recipes", sa.Column("image_url", sa.String(length=2048), nullable=True)
    )
    op.drop_index(op.f("ix_recipes_cuisine"), table_name="recipes")
    op.drop_index(op.f("ix_recipes_source_type"), table_name="recipes")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_recipes_source_type"), "recipes", ["source_type"], unique=False
    )
    op.create_index(op.f("ix_recipes_cuisine"), "recipes", ["cuisine"], unique=False)
    op.drop_column("recipes", "image_url")
    op.drop_index(op.f("ix_organizations_slug"), table_name="organizations")
    op.create_index(
        op.f("ix_organizations_slug"), "organizations", ["slug"], unique=False
    )
    # ### end Alembic commands ###
