"""restore_recipe_filter_indexes

Revision ID: 4c6d1af7b4f4
Revises: 305e0c3cd62a
Create Date: 2026-07-09 22:50:57.015366
"""

from collections.abc import Sequence

revision: str = "4c6d1af7b4f4"
down_revision: str | None = "305e0c3cd62a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
