"""add_ai_provider_configs

Revision ID: de228ebe6a92
Revises: 4c6d1af7b4f4
Create Date: 2026-07-09 23:12:03.732500
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'de228ebe6a92'
down_revision: str | None = '4c6d1af7b4f4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_provider_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('api_key', sa.String(length=512), nullable=False),
    sa.Column('base_url', sa.String(length=1024), nullable=True),
    sa.Column('default_model', sa.String(length=160), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_provider_configs_provider'), 'ai_provider_configs', ['provider'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_provider_configs_provider'), table_name='ai_provider_configs')
    op.drop_table('ai_provider_configs')
    # ### end Alembic commands ###
