/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/ai/capabilities": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Capabilities
     * @description Return AI capabilities for the current deployment.
     */
    get: operations["capabilities_api_v1_ai_capabilities_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/ai/capabilities/{key}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update Capability
     * @description Persist an administrator-controlled AI capability switch.
     */
    patch: operations["update_capability_api_v1_ai_capabilities__key__patch"];
    trace?: never;
  };
  "/api/v1/ai/inventory/analyze-photos": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Analyze Photos
     * @description Analyze food photos to identify inventory items.
     */
    post: operations["analyze_photos_api_v1_ai_inventory_analyze_photos_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/ai/providers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Providers
     * @description List all configured AI providers.
     */
    get: operations["list_providers_api_v1_ai_providers_get"];
    put?: never;
    /**
     * Create Provider
     * @description Add a new AI provider configuration.
     */
    post: operations["create_provider_api_v1_ai_providers_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/ai/providers/known": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Known Providers
     * @description Return the list of known AI provider types that users can configure.
     */
    get: operations["known_providers_api_v1_ai_providers_known_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/ai/providers/{provider_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete Provider
     * @description Delete an AI provider configuration.
     */
    delete: operations["delete_provider_api_v1_ai_providers__provider_id__delete"];
    options?: never;
    head?: never;
    /**
     * Update Provider
     * @description Update an AI provider configuration.
     */
    patch: operations["update_provider_api_v1_ai_providers__provider_id__patch"];
    trace?: never;
  };
  "/api/v1/ai/recipes/enhance": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Enhance Recipe
     * @description Enhance a recipe with AI-powered formatting.
     */
    post: operations["enhance_recipe_api_v1_ai_recipes_enhance_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/ai/recipes/substitutions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Ingredient Substitutions
     * @description Get AI-powered ingredient substitution suggestions.
     */
    post: operations["ingredient_substitutions_api_v1_ai_recipes_substitutions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/ai/shopping/suggest": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Shopping Suggestions
     * @description Get AI-powered shopping list suggestions.
     */
    post: operations["shopping_suggestions_api_v1_ai_shopping_suggest_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/ai/suggestions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Suggest
     * @description Create a provider-free AI suggestion record.
     */
    post: operations["suggest_api_v1_ai_suggestions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/alerts/expiry": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Expiry
     * @description Return inventory expiry alerts.
     */
    get: operations["expiry_api_v1_alerts_expiry_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/imports/jobs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Jobs
     * @description Return import jobs.
     */
    get: operations["jobs_api_v1_imports_jobs_get"];
    put?: never;
    /**
     * Create Job
     * @description Create an import job and execute it in the background.
     */
    post: operations["create_job_api_v1_imports_jobs_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/imports/sources": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Sources
     * @description Return supported import source types.
     */
    get: operations["sources_api_v1_imports_sources_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/imports/sources/{source_key}/credential": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Credential Status
     * @description Return whether credentials exist for a shipped recipe source.
     */
    get: operations["credential_status_api_v1_imports_sources__source_key__credential_get"];
    /**
     * Save Credential
     * @description Encrypt and save credentials for a maintainer-defined recipe source.
     */
    put: operations["save_credential_api_v1_imports_sources__source_key__credential_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/inventory": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Index
     * @description List tracked inventory items.
     */
    get: operations["index_api_v1_inventory_get"];
    put?: never;
    /**
     * Create
     * @description Create a tracked inventory item.
     */
    post: operations["create_api_v1_inventory_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/inventory/import-photos": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Import Photos
     * @description Analyze uploaded photos and insert the identified items into inventory.
     */
    post: operations["import_photos_api_v1_inventory_import_photos_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/recipes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Index
     * @description List recipes stored in Kombu with filtering, sorting, and pagination.
     */
    get: operations["index_api_v1_recipes_get"];
    put?: never;
    /**
     * Create
     * @description Create a recipe.
     */
    post: operations["create_api_v1_recipes_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/recipes/filters": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Filter Values
     * @description Return distinct filter values for the recipe listing.
     */
    get: operations["filter_values_api_v1_recipes_filters_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/recipes/import-url": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Import From Url
     * @description Fetch a public recipe URL, extract it through AI, and create a recipe.
     */
    post: operations["import_from_url_api_v1_recipes_import_url_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/recipes/{recipe_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Show
     * @description Return one recipe.
     */
    get: operations["show_api_v1_recipes__recipe_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/recipes/{recipe_id}/enhancement": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Cached Enhancement
     * @description Return a cached AI enhancement without calling a provider.
     */
    get: operations["cached_enhancement_api_v1_recipes__recipe_id__enhancement_get"];
    put?: never;
    /**
     * Enhance Stored Recipe
     * @description Generate or reuse a cached, structured recipe enhancement.
     */
    post: operations["enhance_stored_recipe_api_v1_recipes__recipe_id__enhancement_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/recipes/{recipe_id}/inventory-suggestions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Suggest From Inventory
     * @description Suggest inventory-backed alternatives for missing ingredients.
     */
    post: operations["suggest_from_inventory_api_v1_recipes__recipe_id__inventory_suggestions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/recipes/{recipe_id}/shopping-list": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Add Recipe To Shopping
     * @description Add missing recipe ingredients in sensible shopping quantities.
     */
    post: operations["add_recipe_to_shopping_api_v1_recipes__recipe_id__shopping_list_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/scanner/capabilities": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Capabilities
     * @description Return supported scanner workflows.
     */
    get: operations["capabilities_api_v1_scanner_capabilities_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/scanner/sessions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Sessions
     * @description Return scanner sessions.
     */
    get: operations["sessions_api_v1_scanner_sessions_get"];
    put?: never;
    /**
     * Create Session
     * @description Create a scanner session.
     */
    post: operations["create_session_api_v1_scanner_sessions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/shopping-list": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Index
     * @description List shopping list items.
     */
    get: operations["index_api_v1_shopping_list_get"];
    put?: never;
    /**
     * Create
     * @description Create a shopping list item.
     */
    post: operations["create_api_v1_shopping_list_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/shopping-list/suggestions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Suggestions
     * @description Suggest useful items from stock, expiry, recipes, and previous runs.
     */
    post: operations["suggestions_api_v1_shopping_list_suggestions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/shopping-list/{item_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update
     * @description Update a shopping list item.
     */
    patch: operations["update_api_v1_shopping_list__item_id__patch"];
    trace?: never;
  };
  "/api/v1/system/features": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Features
     * @description Return persisted feature availability.
     */
    get: operations["features_api_v1_system_features_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/system/features/{key}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update Feature
     * @description Persist an administrator-controlled feature flag.
     */
    patch: operations["update_feature_api_v1_system_features__key__patch"];
    trace?: never;
  };
  "/api/v1/system/overview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Overview
     * @description Return initial dashboard data for the frontend.
     */
    get: operations["overview_api_v1_system_overview_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/system/readiness": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Readiness
     * @description Return readiness for dependency-aware checks.
     */
    get: operations["readiness_api_v1_system_readiness_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Users
     * @description List users for administrator management.
     */
    get: operations["list_users_api_v1_users_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/invites": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Invites
     * @description List pending invitations.
     */
    get: operations["list_invites_api_v1_users_invites_get"];
    put?: never;
    /**
     * Invite User
     * @description Create or replace a pending local invitation.
     */
    post: operations["invite_user_api_v1_users_invites_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/invites/{invite_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Revoke Invite
     * @description Revoke a pending invitation.
     */
    delete: operations["revoke_invite_api_v1_users_invites__invite_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Me
     * @description Return the resolved local user and effective permissions.
     */
    get: operations["me_api_v1_users_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/{user_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update User
     * @description Update a user's role or active status.
     */
    patch: operations["update_user_api_v1_users__user_id__patch"];
    trace?: never;
  };
  "/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Healthz
     * @description Return a lightweight liveness check.
     */
    get: operations["healthz_healthz_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AiCapabilityRead
     * @description AI capability exposed without vendor-specific credentials.
     */
    AiCapabilityRead: {
      /** Description */
      description: string;
      /** Enabled */
      enabled: boolean;
      /** Key */
      key: string;
      /** Label */
      label: string;
    };
    /**
     * AiCapabilityUpdate
     * @description Administrator update for an AI capability switch.
     */
    AiCapabilityUpdate: {
      /** Enabled */
      enabled: boolean;
    };
    /**
     * AiProviderConfigCreate
     * @description Create a new AI provider configuration.
     */
    AiProviderConfigCreate: {
      /** Api Key */
      api_key: string;
      /** Base Url */
      base_url?: string | null;
      /** Default Model */
      default_model: string;
      /**
       * Is Enabled
       * @default true
       */
      is_enabled: boolean;
      /** Label */
      label: string;
      /** Provider */
      provider: string;
    };
    /**
     * AiProviderConfigRead
     * @description AI provider configuration response.
     */
    AiProviderConfigRead: {
      /** Api Key Configured */
      api_key_configured: boolean;
      /** Api Key Hint */
      api_key_hint?: string | null;
      /** Base Url */
      base_url: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Default Model */
      default_model: string;
      /** Id */
      id: number;
      /** Is Enabled */
      is_enabled: boolean;
      /** Label */
      label: string;
      /** Provider */
      provider: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * AiProviderConfigUpdate
     * @description Update an AI provider configuration.
     */
    AiProviderConfigUpdate: {
      /** Api Key */
      api_key?: string | null;
      /** Base Url */
      base_url?: string | null;
      /** Default Model */
      default_model?: string | null;
      /** Is Enabled */
      is_enabled?: boolean | null;
      /** Label */
      label?: string | null;
    };
    /**
     * AiSuggestionCreate
     * @description AI suggestion request.
     */
    AiSuggestionCreate: {
      /** Context */
      context?: string | null;
      /** Prompt */
      prompt: string;
    };
    /**
     * AiSuggestionRead
     * @description AI suggestion response.
     */
    AiSuggestionRead: {
      /** Context */
      context: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Id */
      id: number;
      /** Prompt */
      prompt: string;
      /** Suggestion */
      suggestion: string;
    };
    /** Body_import_photos_api_v1_inventory_import_photos_post */
    Body_import_photos_api_v1_inventory_import_photos_post: {
      /**
       * Photos
       * @description Inventory photos
       */
      photos: string[];
    };
    /**
     * CurrentUserRead
     * @description Current user bootstrap response.
     */
    CurrentUserRead: {
      /** Auth Provider */
      auth_provider: string;
      /** Display Name */
      display_name: string;
      /** Email */
      email: string;
      /** Id */
      id: number;
      /** Permissions */
      permissions: string[];
      /** Role */
      role: string;
    };
    /**
     * ExpiryAlertRead
     * @description Expiry alert response for an inventory item.
     */
    ExpiryAlertRead: {
      /** Days Until Expiry */
      days_until_expiry: number;
      /**
       * Expires On
       * Format: date
       */
      expires_on: string;
      /** Item Id */
      item_id: number;
      location: components["schemas"]["InventoryLocation"];
      /** Name */
      name: string;
      /** Severity */
      severity: string;
    };
    /**
     * FeatureFlag
     * @description Feature availability shown to the frontend.
     */
    FeatureFlag: {
      /** Description */
      description: string;
      /** Enabled */
      enabled: boolean;
      /** Key */
      key: string;
      /** Label */
      label: string;
    };
    /**
     * FeatureFlagUpdate
     * @description Administrator update for a persisted feature flag.
     */
    FeatureFlagUpdate: {
      /** Enabled */
      enabled: boolean;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * HealthRead
     * @description Public liveness response.
     */
    HealthRead: {
      /** Service */
      service: string;
      /** Status */
      status: string;
      /** Version */
      version: string;
    };
    /**
     * ImportCredentialRead
     * @description Credential status that never exposes stored secret material.
     */
    ImportCredentialRead: {
      /** Account Name */
      account_name: string | null;
      /** Configured */
      configured: boolean;
      /** Source Key */
      source_key: string;
    };
    /**
     * ImportCredentialUpdate
     * @description User-supplied account and secret for a maintainer-defined source.
     */
    ImportCredentialUpdate: {
      /** Account Name */
      account_name: string;
      /** Secret */
      secret: string;
    };
    /**
     * ImportJobCreate
     * @description Import job creation request.
     */
    ImportJobCreate: {
      /** Source Name */
      source_name: string;
      /** Source Type */
      source_type: string;
    };
    /**
     * ImportJobRead
     * @description Import job response.
     */
    ImportJobRead: {
      /** Completed At */
      completed_at: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Error Message */
      error_message: string | null;
      /** Id */
      id: number;
      /** Imported Records */
      imported_records: number;
      /** Source Name */
      source_name: string;
      /** Source Type */
      source_type: string;
      status: components["schemas"]["ImportJobStatus"];
      /** Total Records */
      total_records: number;
    };
    /**
     * ImportJobStatus
     * @description Lifecycle states for recipe import jobs.
     * @enum {string}
     */
    ImportJobStatus: "queued" | "running" | "completed" | "failed";
    /**
     * ImportSourceRead
     * @description Import source that Kombu can prepare for users.
     */
    ImportSourceRead: {
      /** Description */
      description: string;
      /** Key */
      key: string;
      /** Label */
      label: string;
      /** Ready For Import */
      ready_for_import: boolean;
      /** Source Type */
      source_type: string;
    };
    /** IngredientSubstitutionRequest */
    IngredientSubstitutionRequest: {
      /** Expiry Items */
      expiry_items?: {
        [key: string]: string;
      }[];
      /** Inventory Items */
      inventory_items?: {
        [key: string]: string;
      }[];
      /** Recipe Ingredients */
      recipe_ingredients?: string[];
      /** Recipe Title */
      recipe_title: string;
    };
    /**
     * IngredientSuggestionRead
     * @description Inventory match and alternatives for one recipe ingredient.
     */
    IngredientSuggestionRead: {
      /** Available */
      available: boolean;
      /** Name */
      name: string;
      /** Substitutions */
      substitutions?: string[];
    };
    /**
     * InventoryItemCreate
     * @description Inventory item creation request.
     */
    InventoryItemCreate: {
      /** Expires On */
      expires_on?: string | null;
      /** @default pantry */
      location: components["schemas"]["InventoryLocation"];
      /** Name */
      name: string;
      /** Notes */
      notes?: string | null;
      /** Opened On */
      opened_on?: string | null;
      /**
       * Quantity
       * @default 1
       */
      quantity: number;
      /** Source */
      source?: string | null;
      /** Unit */
      unit?: string | null;
    };
    /**
     * InventoryItemRead
     * @description Inventory item response.
     */
    InventoryItemRead: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Expires On */
      expires_on?: string | null;
      /** Id */
      id: number;
      /** @default pantry */
      location: components["schemas"]["InventoryLocation"];
      /** Name */
      name: string;
      /** Notes */
      notes?: string | null;
      /** Opened On */
      opened_on?: string | null;
      /**
       * Quantity
       * @default 1
       */
      quantity: number;
      /** Source */
      source?: string | null;
      /** Unit */
      unit?: string | null;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * InventoryLocation
     * @description Common locations where inventory items can be stored.
     * @enum {string}
     */
    InventoryLocation: "pantry" | "fridge" | "freezer" | "counter" | "other";
    /**
     * InventoryPhotoImportRead
     * @description Items created after analyzing uploaded inventory photos.
     */
    InventoryPhotoImportRead: {
      /** Items */
      items: components["schemas"]["InventoryItemRead"][];
    };
    /**
     * KnownProviderRead
     * @description A known AI provider type.
     */
    KnownProviderRead: {
      /** Docs */
      docs: string;
      /** Key */
      key: string;
      /** Label */
      label: string;
    };
    /**
     * NavigationItem
     * @description Frontend navigation item provided by the API.
     */
    NavigationItem: {
      /** Href */
      href: string;
      /** Label */
      label: string;
      /** Section */
      section: string;
    };
    /**
     * OverviewMetric
     * @description Dashboard metric for the system overview.
     */
    OverviewMetric: {
      /** Description */
      description: string;
      /** Key */
      key: string;
      /** Label */
      label: string;
      /** Value */
      value: number;
    };
    /** PhotoAnalysisRequest */
    PhotoAnalysisRequest: {
      /** Image Paths */
      image_paths?: string[];
    };
    /**
     * ReadinessRead
     * @description Readiness result for services that need dependencies.
     */
    ReadinessRead: {
      /** Database */
      database: string;
      /** Status */
      status: string;
    };
    /**
     * RecipeCreate
     * @description Recipe creation request.
     */
    RecipeCreate: {
      /** Cook Minutes */
      cook_minutes?: number | null;
      /** Cuisine */
      cuisine?: string | null;
      /** Image Url */
      image_url?: string | null;
      /** Ingredients */
      ingredients?: components["schemas"]["RecipeIngredientCreate"][];
      /** Instructions */
      instructions?: string | null;
      /**
       * Is Favorite
       * @default false
       */
      is_favorite: boolean;
      /** Prep Minutes */
      prep_minutes?: number | null;
      /** @default user */
      source_type: components["schemas"]["RecipeSourceType"];
      /** Source Url */
      source_url?: string | null;
      /** Summary */
      summary?: string | null;
      /** Title */
      title: string;
      /** Yield Servings */
      yield_servings?: number | null;
    };
    /** RecipeEnhanceRequest */
    RecipeEnhanceRequest: {
      /** Recipe Ingredients */
      recipe_ingredients?: string[];
      /** Recipe Instructions */
      recipe_instructions?: string | null;
      /** Recipe Summary */
      recipe_summary?: string | null;
      /** Recipe Title */
      recipe_title: string;
    };
    /**
     * RecipeEnhancementRead
     * @description Cached AI enhancement for a recipe.
     */
    RecipeEnhancementRead: {
      /** Cached */
      cached: boolean;
      /**
       * Generated At
       * Format: date-time
       */
      generated_at: string;
      /** Instructions */
      instructions: string;
      /** Summary */
      summary: string;
      /** Tips */
      tips?: string[];
      /** Title */
      title: string;
    };
    /**
     * RecipeFilterValues
     * @description Available filter values for the recipe listing sidebar.
     */
    RecipeFilterValues: {
      /** Cuisines */
      cuisines: string[];
      /** Ingredients */
      ingredients: string[];
      /** Max Cook Minutes */
      max_cook_minutes?: number | null;
      /** Max Prep Minutes */
      max_prep_minutes?: number | null;
      /** Source Types */
      source_types: string[];
    };
    /** RecipeImportUrlRequest */
    RecipeImportUrlRequest: {
      /** Url */
      url: string;
    };
    /**
     * RecipeIngredientCreate
     * @description Ingredient input for recipe creation.
     */
    RecipeIngredientCreate: {
      /** Name */
      name: string;
      /** Note */
      note?: string | null;
      /** Quantity */
      quantity?: number | null;
      /** Unit */
      unit?: string | null;
    };
    /**
     * RecipeIngredientRead
     * @description Ingredient response for stored recipes.
     */
    RecipeIngredientRead: {
      /** Id */
      id: number;
      /** Name */
      name: string;
      /** Note */
      note?: string | null;
      /** Position */
      position: number;
      /** Quantity */
      quantity?: number | null;
      /** Unit */
      unit?: string | null;
    };
    /**
     * RecipeListResponse
     * @description Paginated recipe list.
     */
    RecipeListResponse: {
      /** Items */
      items: components["schemas"]["RecipeRead"][];
      /** Page */
      page: number;
      /** Per Page */
      per_page: number;
      /** Total */
      total: number;
    };
    /**
     * RecipeRead
     * @description Recipe response with ingredients.
     */
    RecipeRead: {
      /** Cook Minutes */
      cook_minutes: number | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Cuisine */
      cuisine: string | null;
      /** Id */
      id: number;
      /** Image Url */
      image_url: string | null;
      /** Ingredients */
      ingredients: components["schemas"]["RecipeIngredientRead"][];
      /** Instructions */
      instructions: string | null;
      /** Is Favorite */
      is_favorite: boolean;
      /** Prep Minutes */
      prep_minutes: number | null;
      source_type: components["schemas"]["RecipeSourceType"];
      /** Source Url */
      source_url: string | null;
      /** Summary */
      summary: string | null;
      /** Title */
      title: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Yield Servings */
      yield_servings: number | null;
    };
    /**
     * RecipeShoppingResult
     * @description Result of intelligently adding missing recipe items to shopping.
     */
    RecipeShoppingResult: {
      /** Added */
      added?: string[];
      /** Skipped Available */
      skipped_available?: string[];
      /** Skipped Household Quantity */
      skipped_household_quantity?: string[];
    };
    /**
     * RecipeSourceType
     * @description Where a recipe originated before it was stored in Kombu.
     * @enum {string}
     */
    RecipeSourceType: "user" | "import" | "web" | "ai";
    /**
     * ScanSessionCreate
     * @description Scan session creation request.
     */
    ScanSessionCreate: {
      /** Device Hint */
      device_hint?: string | null;
      /** Raw Payload */
      raw_payload?: string | null;
      /** Scan Type */
      scan_type: string;
    };
    /**
     * ScanSessionRead
     * @description Scan session response.
     */
    ScanSessionRead: {
      /** Completed At */
      completed_at: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Device Hint */
      device_hint: string | null;
      /** Id */
      id: number;
      /** Raw Payload */
      raw_payload: string | null;
      /** Result Summary */
      result_summary: string | null;
      /** Scan Type */
      scan_type: string;
      status: components["schemas"]["ScanSessionStatus"];
    };
    /**
     * ScanSessionStatus
     * @description Lifecycle states for scanner capture sessions.
     * @enum {string}
     */
    ScanSessionStatus: "created" | "processing" | "completed" | "failed";
    /**
     * ScannerCapabilityRead
     * @description Scanner capability response.
     */
    ScannerCapabilityRead: {
      /** Description */
      description: string;
      /** Key */
      key: string;
      /** Label */
      label: string;
      /** Requires Hardware */
      requires_hardware: boolean;
    };
    /**
     * ShoppingItemStatus
     * @description Lifecycle states for a shopping list item.
     * @enum {string}
     */
    ShoppingItemStatus: "needed" | "purchased";
    /**
     * ShoppingListItemCreate
     * @description Shopping list item creation request.
     */
    ShoppingListItemCreate: {
      /** Category */
      category?: string | null;
      /** Linked Inventory Item Id */
      linked_inventory_item_id?: number | null;
      /** Name */
      name: string;
      /**
       * Quantity
       * @default 1
       */
      quantity: number;
      /** Recipe Id */
      recipe_id?: number | null;
      /** @default needed */
      status: components["schemas"]["ShoppingItemStatus"];
      /** Unit */
      unit?: string | null;
    };
    /**
     * ShoppingListItemRead
     * @description Shopping list item response.
     */
    ShoppingListItemRead: {
      /** Category */
      category?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Id */
      id: number;
      /** Linked Inventory Item Id */
      linked_inventory_item_id?: number | null;
      /** Name */
      name: string;
      /**
       * Quantity
       * @default 1
       */
      quantity: number;
      /** Recipe Id */
      recipe_id?: number | null;
      /** @default needed */
      status: components["schemas"]["ShoppingItemStatus"];
      /** Unit */
      unit?: string | null;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * ShoppingListItemUpdate
     * @description Partial shopping list item update request.
     */
    ShoppingListItemUpdate: {
      /** Category */
      category?: string | null;
      /** Quantity */
      quantity?: number | null;
      status?: components["schemas"]["ShoppingItemStatus"] | null;
      /** Unit */
      unit?: string | null;
    };
    /** ShoppingSuggestRequest */
    ShoppingSuggestRequest: {
      /** Frequently Cooked */
      frequently_cooked?: string[];
      /** Inventory Items */
      inventory_items?: {
        [key: string]: string;
      }[];
      /** Planned Recipes */
      planned_recipes?: {
        [key: string]: string;
      }[];
      /** Shopping History */
      shopping_history?: {
        [key: string]: string;
      }[];
    };
    /**
     * ShoppingSuggestionRead
     * @description One context-aware proposal for the next shopping run.
     */
    ShoppingSuggestionRead: {
      /**
       * Category
       * @default Other
       */
      category: string;
      /** Item Name */
      item_name: string;
      /**
       * Priority
       * @default medium
       */
      priority: string;
      /** Reason */
      reason: string;
    };
    /**
     * ShoppingSuggestionsRead
     * @description Shopping proposals derived from the user's own kitchen activity.
     */
    ShoppingSuggestionsRead: {
      /** Suggestions */
      suggestions: components["schemas"]["ShoppingSuggestionRead"][];
    };
    /**
     * SystemOverviewRead
     * @description Initial dashboard payload for Kombu.
     */
    SystemOverviewRead: {
      /** App Name */
      app_name: string;
      /** Environment */
      environment: string;
      /** Features */
      features: components["schemas"]["FeatureFlag"][];
      /** Metrics */
      metrics: components["schemas"]["OverviewMetric"][];
      /** Navigation */
      navigation: components["schemas"]["NavigationItem"][];
    };
    /**
     * UserInviteCreate
     * @description Create a pending user invitation.
     */
    UserInviteCreate: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** @default viewer */
      role: components["schemas"]["UserRole"];
    };
    /**
     * UserInviteRead
     * @description Pending invitation safe to display to administrators.
     */
    UserInviteRead: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Id */
      id: number;
      role: components["schemas"]["UserRole"];
    };
    /**
     * UserRead
     * @description Administrator-facing user summary.
     */
    UserRead: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Display Name */
      display_name: string;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Id */
      id: number;
      /** Is Active */
      is_active: boolean;
      role: components["schemas"]["UserRole"];
    };
    /**
     * UserRole
     * @description Supported user roles for the initial multi-user model.
     * @enum {string}
     */
    UserRole: "admin" | "editor" | "viewer";
    /**
     * UserUpdate
     * @description Fields an administrator can change on a user.
     */
    UserUpdate: {
      /** Is Active */
      is_active?: boolean | null;
      role?: components["schemas"]["UserRole"] | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  capabilities_api_v1_ai_capabilities_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AiCapabilityRead"][];
        };
      };
    };
  };
  update_capability_api_v1_ai_capabilities__key__patch: {
    parameters: {
      query?: never;
      header?: {
        "x-kombu-user-id"?: number | null;
      };
      path: {
        key: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AiCapabilityUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AiCapabilityRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  analyze_photos_api_v1_ai_inventory_analyze_photos_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PhotoAnalysisRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_providers_api_v1_ai_providers_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AiProviderConfigRead"][];
        };
      };
    };
  };
  create_provider_api_v1_ai_providers_post: {
    parameters: {
      query?: never;
      header?: {
        "x-kombu-user-id"?: number | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AiProviderConfigCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AiProviderConfigRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  known_providers_api_v1_ai_providers_known_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["KnownProviderRead"][];
        };
      };
    };
  };
  delete_provider_api_v1_ai_providers__provider_id__delete: {
    parameters: {
      query?: never;
      header?: {
        "x-kombu-user-id"?: number | null;
      };
      path: {
        provider_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_provider_api_v1_ai_providers__provider_id__patch: {
    parameters: {
      query?: never;
      header?: {
        "x-kombu-user-id"?: number | null;
      };
      path: {
        provider_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AiProviderConfigUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AiProviderConfigRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  enhance_recipe_api_v1_ai_recipes_enhance_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RecipeEnhanceRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  ingredient_substitutions_api_v1_ai_recipes_substitutions_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["IngredientSubstitutionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  shopping_suggestions_api_v1_ai_shopping_suggest_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ShoppingSuggestRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  suggest_api_v1_ai_suggestions_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AiSuggestionCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AiSuggestionRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  expiry_api_v1_alerts_expiry_get: {
    parameters: {
      query?: {
        days?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExpiryAlertRead"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  jobs_api_v1_imports_jobs_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportJobRead"][];
        };
      };
    };
  };
  create_job_api_v1_imports_jobs_post: {
    parameters: {
      query?: never;
      header?: {
        "x-kombu-user-id"?: number | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ImportJobCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportJobRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  sources_api_v1_imports_sources_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportSourceRead"][];
        };
      };
    };
  };
  credential_status_api_v1_imports_sources__source_key__credential_get: {
    parameters: {
      query?: never;
      header?: {
        "x-kombu-user-id"?: number | null;
      };
      path: {
        source_key: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportCredentialRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  save_credential_api_v1_imports_sources__source_key__credential_put: {
    parameters: {
      query?: never;
      header?: {
        "x-kombu-user-id"?: number | null;
      };
      path: {
        source_key: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ImportCredentialUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportCredentialRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  index_api_v1_inventory_get: {
    parameters: {
      query?: {
        location?: components["schemas"]["InventoryLocation"] | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InventoryItemRead"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_api_v1_inventory_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InventoryItemCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InventoryItemRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  import_photos_api_v1_inventory_import_photos_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_import_photos_api_v1_inventory_import_photos_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InventoryPhotoImportRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  index_api_v1_recipes_get: {
    parameters: {
      query?: {
        search?: string | null;
        skip?: number;
        limit?: number;
        cuisine?: string | null;
        source_type?: string | null;
        ingredient?: string | null;
        max_total_minutes?: number | null;
        favorites_only?: boolean;
        has_image?: boolean | null;
        sort_by?: string;
        sort_order?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RecipeListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_api_v1_recipes_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RecipeCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RecipeRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  filter_values_api_v1_recipes_filters_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RecipeFilterValues"];
        };
      };
    };
  };
  import_from_url_api_v1_recipes_import_url_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RecipeImportUrlRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RecipeRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  show_api_v1_recipes__recipe_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        recipe_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RecipeRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  cached_enhancement_api_v1_recipes__recipe_id__enhancement_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        recipe_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json":
            | components["schemas"]["RecipeEnhancementRead"]
            | null;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  enhance_stored_recipe_api_v1_recipes__recipe_id__enhancement_post: {
    parameters: {
      query?: {
        regenerate?: boolean;
      };
      header?: never;
      path: {
        recipe_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RecipeEnhancementRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  suggest_from_inventory_api_v1_recipes__recipe_id__inventory_suggestions_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        recipe_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IngredientSuggestionRead"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  add_recipe_to_shopping_api_v1_recipes__recipe_id__shopping_list_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        recipe_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RecipeShoppingResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  capabilities_api_v1_scanner_capabilities_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ScannerCapabilityRead"][];
        };
      };
    };
  };
  sessions_api_v1_scanner_sessions_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ScanSessionRead"][];
        };
      };
    };
  };
  create_session_api_v1_scanner_sessions_post: {
    parameters: {
      query?: never;
      header?: {
        "x-kombu-user-id"?: number | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ScanSessionCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ScanSessionRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  index_api_v1_shopping_list_get: {
    parameters: {
      query?: {
        status_filter?: components["schemas"]["ShoppingItemStatus"] | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ShoppingListItemRead"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_api_v1_shopping_list_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ShoppingListItemCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ShoppingListItemRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  suggestions_api_v1_shopping_list_suggestions_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ShoppingSuggestionsRead"];
        };
      };
    };
  };
  update_api_v1_shopping_list__item_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        item_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ShoppingListItemUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ShoppingListItemRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  features_api_v1_system_features_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FeatureFlag"][];
        };
      };
    };
  };
  update_feature_api_v1_system_features__key__patch: {
    parameters: {
      query?: never;
      header?: {
        "x-kombu-user-id"?: number | null;
      };
      path: {
        key: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FeatureFlagUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FeatureFlag"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  overview_api_v1_system_overview_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SystemOverviewRead"];
        };
      };
    };
  };
  readiness_api_v1_system_readiness_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadinessRead"];
        };
      };
    };
  };
  list_users_api_v1_users_get: {
    parameters: {
      query?: never;
      header?: {
        "x-kombu-user-id"?: number | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserRead"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_invites_api_v1_users_invites_get: {
    parameters: {
      query?: never;
      header?: {
        "x-kombu-user-id"?: number | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserInviteRead"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  invite_user_api_v1_users_invites_post: {
    parameters: {
      query?: never;
      header?: {
        "x-kombu-user-id"?: number | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserInviteCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserInviteRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  revoke_invite_api_v1_users_invites__invite_id__delete: {
    parameters: {
      query?: never;
      header?: {
        "x-kombu-user-id"?: number | null;
      };
      path: {
        invite_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  me_api_v1_users_me_get: {
    parameters: {
      query?: never;
      header?: {
        "x-kombu-user-id"?: number | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CurrentUserRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_user_api_v1_users__user_id__patch: {
    parameters: {
      query?: never;
      header?: {
        "x-kombu-user-id"?: number | null;
      };
      path: {
        user_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  healthz_healthz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthRead"];
        };
      };
    };
  };
}
